# Generated by Django 3.2 on 2022-07-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0002_auto_20220726_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fisrt_name',
            new_name='first_name',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name', 'last_name'], name='store_custo_first_n_8f83e0_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customer',
        ),
    ]
