# Generated by Django 3.2 on 2022-07-26 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0003_auto_20220726_0737'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
