# Generated by Django 3.2 on 2022-07-26 02:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0004_alter_customer_table'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO store_collection (title) 
        VALUES ("collection1")
        """, """
        DELETE FROM store_collection WHERE title="collection1"
        """)
    ]
