# Generated by Django 3.2 on 2022-07-27 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0005_auto_20220726_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['discount']},
        ),
    ]
