# Generated by Django 3.2 on 2022-07-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0006_auto_20220727_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
    ]
