# Generated by Django 3.2 on 2022-07-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0008_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
