# Generated by Django 3.2 on 2022-07-28 22:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0012_auto_20220729_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
